{
 "title": "Binance Asset Dashboard",
 "tags": [
  "cassandra",
  "binance"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Asset Prices Over Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "keyspace": "assets",
     "target": "SELECT asset_name, asset_price, collected_at FROM assets",
     "timestamp": "collected_at"
    }
   ]
  },
  {
   "title": "Latest Asset Price",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "keyspace": "assets",
     "target": "SELECT asset_name, asset_price FROM assets LIMIT 1"
    }
   ]
  },
  {
   "title": "Asset Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "keyspace": "assets",
     "target": "SELECT asset_name, asset_price FROM assets"
    }
   ]
  }
 ]
}