apiVersion: 1

datasources:
  - name: Cassandra
    uid: Cassandra
    type: hadesarchitect-cassandra-datasource
    access: proxy
    orgId: 1
    isDefault: true
    version: 2
    editable: true
    url: binance-cassandra:9042
    jsonData:
      keyspace: assets
      username: adminadmin
      port: 9042
      consistency: 'ONE'
    secureJsonData:
      password: adminadmin